### PR TITLE
fix(tests): move category assertions into guards to prevent log event ordering races

### LINKED ISSUE #338: Intermittent integration test failure of test_integration_logextractor_unknown_with_category
from https://github.com/peer-observer/peer-observer/actions/runs/21064896594/job/60580105023?pr=337
```
---- test_integration_logextractor_unknown_with_category stdout ----
test that we receive unknown log events with category
2026-01-16T11:31:44.747Z INFO  [integration] Running node1 with arg: -debug=net
2026-01-16T11:31:44.747Z INFO  [integration] env BITCOIND_EXE=Ok("/nix/store/rqhjkp8ggnfbrjw9xd3kfxm2qszdv2np-bitcoind-30.0/bin/bitcoind")
2026-01-16T11:31:44.747Z INFO  [integration] exe_path=Ok("/nix/store/rqhjkp8ggnfbrjw9xd3kfxm2qszdv2np-bitcoind-30.0/bin/bitcoind")
2026-01-16T11:31:44.747Z INFO  [integration] Using bitcoind at '/nix/store/rqhjkp8ggnfbrjw9xd3kfxm2qszdv2np-bitcoind-30.0/bin/bitcoind'
2026-01-16T11:31:44.948Z DEBUG [corepc] request: createwallet ["default"]
2026-01-16T11:31:47.056Z TRACE [corepc] response for createwallet: {"name":"default"}
2026-01-16T11:31:47.056Z DEBUG [corepc] request: getblockchaininfo []
2026-01-16T11:31:47.072Z TRACE [corepc] response for getblockchaininfo: {"chain":"regtest","blocks":0,"headers":0,"bestblockhash":"0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206","bits":"207fffff","target":"7fffff0000000000000000000000000000000000000000000000000000000000","difficulty":4.656542373906925e-10,"time":1296688602,"mediantime":1296688602,"verificationprogress":2.119203030044969e-06,"initialblockdownload":true,"chainwork":"0000000000000000000000000000000000000000000000000000000000000002","size_on_disk":293,"pruned":false,"warnings":[]}
2026-01-16T11:31:47.072Z INFO  [integration] env BITCOIND_EXE=Ok("/nix/store/rqhjkp8ggnfbrjw9xd3kfxm2qszdv2np-bitcoind-30.0/bin/bitcoind")
2026-01-16T11:31:47.072Z INFO  [integration] exe_path=Ok("/nix/store/rqhjkp8ggnfbrjw9xd3kfxm2qszdv2np-bitcoind-30.0/bin/bitcoind")
2026-01-16T11:31:47.072Z INFO  [integration] Using bitcoind at '/nix/store/rqhjkp8ggnfbrjw9xd3kfxm2qszdv2np-bitcoind-30.0/bin/bitcoind'
2026-01-16T11:31:47.285Z DEBUG [corepc] request: createwallet ["default"]
2026-01-16T11:31:49.419Z TRACE [corepc] response for createwallet: {"name":"default"}
2026-01-16T11:31:49.419Z DEBUG [corepc] request: getblockchaininfo []
2026-01-16T11:31:49.430Z TRACE [corepc] response for getblockchaininfo: {"chain":"regtest","blocks":0,"headers":0,"bestblockhash":"0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206","bits":"207fffff","target":"7fffff0000000000000000000000000000000000000000000000000000000000","difficulty":4.656542373906925e-10,"time":1296688602,"mediantime":1296688602,"verificationprogress":2.119203021062926e-06,"initialblockdownload":true,"chainwork":"0000000000000000000000000000000000000000000000000000000000000002","size_on_disk":293,"pruned":false,"warnings":[]}
2026-01-16T11:31:49.430Z DEBUG [shared::testing::nats_server] attempting to use port=60405 for the testing NATS server (attempt=1)
2026-01-16T11:31:49.430Z INFO  [shared::testing::nats_server] Starting NATS server with: /nix/store/qh1xkr66wsddlfzfv4rzbp2ifnj0qbsk-nats-server-2.12.2/bin/nats-server --port=60405 --addr=127.0.0.1
2026-01-16T11:31:49.469Z DEBUG [shared::testing::nats_server] [14983] 2026/01/16 11:31:49.469166 [INF] Starting nats-server
2026-01-16T11:31:49.469Z DEBUG [shared::testing::nats_server] [14983] 2026/01/16 11:31:49.469528 [INF]   Version:  2.12.2
2026-01-16T11:31:49.469Z DEBUG [shared::testing::nats_server] [14983] 2026/01/16 11:31:49.469616 [INF]   Git:      [not set]
2026-01-16T11:31:49.469Z DEBUG [shared::testing::nats_server] [14983] 2026/01/16 11:31:49.469664 [INF]   Name:     NAL2PZBPSGHOF3CBAGJJ6C4EN345QEWPZ4HVFPCNPIQIP6HR2EALK2F4
2026-01-16T11:31:49.469Z DEBUG [shared::testing::nats_server] [14983] 2026/01/16 11:31:49.469726 [INF]   ID:       NAL2PZBPSGHOF3CBAGJJ6C4EN345QEWPZ4HVFPCNPIQIP6HR2EALK2F4
2026-01-16T11:31:49.470Z DEBUG [shared::testing::nats_server] [14983] 2026/01/16 11:31:49.470675 [INF] Listening for client connections on 127.0.0.1:60405
2026-01-16T11:31:49.481Z DEBUG [shared::testing::nats_server] [14983] 2026/01/16 11:31:49.470820 [INF] Server is ready
2026-01-16T11:31:49.487Z INFO  [integration] Created named pipe at /home/runner/work/_temp/nix-shell-2800-1231719446/.tmpFwZ3e3/bitcoind_pipe
2026-01-16T11:31:49.487Z INFO  [integration] Running: bash -c 'tail -f /home/runner/work/_temp/nix-shell-2800-1231719446/.tmpFwZ3e3/regtest/debug.log > /home/runner/work/_temp/nix-shell-2800-1231719446/.tmpFwZ3e3/bitcoind_pipe'
2026-01-16T11:31:49.493Z DEBUG [shared::nats_util] Connecting to NATS-server at 127.0.0.1:60405 without authentification
2026-01-16T11:31:49.494Z INFO  [log_extractor] Connected to NATS server at 127.0.0.1:60405
2026-01-16T11:31:49.494Z INFO  [log_extractor] Opening bitcoind log pipe at /home/runner/work/_temp/nix-shell-2800-1231719446/.tmpFwZ3e3/bitcoind_pipe...
2026-01-16T11:31:49.506Z INFO  [log_extractor] Opened bitcoind log pipe at /home/runner/work/_temp/nix-shell-2800-1231719446/.tmpFwZ3e3/bitcoind_pipe
2026-01-16T11:31:49.506Z INFO  [log_extractor] Started reading lines from bitcoind log pipe at /home/runner/work/_temp/nix-shell-2800-1231719446/.tmpFwZ3e3/bitcoind_pipe
2026-01-16T11:31:49.506Z TRACE [log_extractor] Read log line: 2026-01-16T11:31:47Z [net] received: getheaders (69 bytes) peer=0
2026-01-16T11:31:49.506Z TRACE [shared::protobuf::event] creating new Event: LogExtractor(Log { log_timestamp: 1768563107000000, category: Net, threadname: "", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "received: getheaders (69 bytes) peer=0" })) })
2026-01-16T11:31:49.506Z TRACE [log_extractor] published log into NATS: Event { timestamp: 1768563109506, peer_observer_event: Some(LogExtractor(Log { log_timestamp: 1768563107000000, category: Net, threadname: "", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "received: getheaders (69 bytes) peer=0" })) })) }
2026-01-16T11:31:49.506Z TRACE [log_extractor] Read log line: 2026-01-16T11:31:47Z [net] getheaders -1 to end from peer=0
2026-01-16T11:31:49.506Z TRACE [shared::protobuf::event] creating new Event: LogExtractor(Log { log_timestamp: 1768563107000000, category: Net, threadname: "", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "getheaders -1 to end from peer=0" })) })
2026-01-16T11:31:49.506Z TRACE [log_extractor] published log into NATS: Event { timestamp: 1768563109506, peer_observer_event: Some(LogExtractor(Log { log_timestamp: 1768563107000000, category: Net, threadname: "", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "getheaders -1 to end from peer=0" })) })) }
2026-01-16T11:31:49.506Z TRACE [log_extractor] Read log line: 2026-01-16T11:31:47Z [net] sending headers (1 bytes) peer=0
2026-01-16T11:31:49.506Z TRACE [shared::protobuf::event] creating new Event: LogExtractor(Log { log_timestamp: 1768563107000000, category: Net, threadname: "", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "sending headers (1 bytes) peer=0" })) })
2026-01-16T11:31:49.506Z TRACE [log_extractor] published log into NATS: Event { timestamp: 1768563109506, peer_observer_event: Some(LogExtractor(Log { log_timestamp: 1768563107000000, category: Net, threadname: "", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "sending headers (1 bytes) peer=0" })) })) }
2026-01-16T11:31:49.506Z TRACE [log_extractor] Read log line: 2026-01-16T11:31:47Z [net] received: feefilter (8 bytes) peer=0
2026-01-16T11:31:49.506Z TRACE [shared::protobuf::event] creating new Event: LogExtractor(Log { log_timestamp: 1768563107000000, category: Net, threadname: "", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "received: feefilter (8 bytes) peer=0" })) })
2026-01-16T11:31:49.506Z TRACE [log_extractor] published log into NATS: Event { timestamp: 1768563109506, peer_observer_event: Some(LogExtractor(Log { log_timestamp: 1768563107000000, category: Net, threadname: "", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "received: feefilter (8 bytes) peer=0" })) })) }
2026-01-16T11:31:49.506Z TRACE [log_extractor] Read log line: 2026-01-16T11:31:47Z [net] received: feefilter of 0.09936506 BTC/kvB from peer=0
2026-01-16T11:31:49.506Z TRACE [shared::protobuf::event] creating new Event: LogExtractor(Log { log_timestamp: 1768563107000000, category: Net, threadname: "", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "received: feefilter of 0.09936506 BTC/kvB from peer=0" })) })
2026-01-16T11:31:49.506Z TRACE [log_extractor] published log into NATS: Event { timestamp: 1768563109506, peer_observer_event: Some(LogExtractor(Log { log_timestamp: 1768563107000000, category: Net, threadname: "", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "received: feefilter of 0.09936506 BTC/kvB from peer=0" })) })) }
2026-01-16T11:31:49.507Z TRACE [log_extractor] Read log line: 2026-01-16T11:31:47Z [net] received: pong (8 bytes) peer=0
2026-01-16T11:31:49.507Z TRACE [shared::protobuf::event] creating new Event: LogExtractor(Log { log_timestamp: 1768563107000000, category: Net, threadname: "", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "received: pong (8 bytes) peer=0" })) })
2026-01-16T11:31:49.507Z TRACE [log_extractor] published log into NATS: Event { timestamp: 1768563109507, peer_observer_event: Some(LogExtractor(Log { log_timestamp: 1768563107000000, category: Net, threadname: "", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "received: pong (8 bytes) peer=0" })) })) }
2026-01-16T11:31:49.507Z TRACE [log_extractor] Read log line: 2026-01-16T11:31:47Z [net] received: headers (1 bytes) peer=0
2026-01-16T11:31:49.507Z TRACE [shared::protobuf::event] creating new Event: LogExtractor(Log { log_timestamp: 1768563107000000, category: Net, threadname: "", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "received: headers (1 bytes) peer=0" })) })
2026-01-16T11:31:49.507Z TRACE [log_extractor] published log into NATS: Event { timestamp: 1768563109507, peer_observer_event: Some(LogExtractor(Log { log_timestamp: 1768563107000000, category: Net, threadname: "", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "received: headers (1 bytes) peer=0" })) })) }
2026-01-16T11:31:49.507Z TRACE [log_extractor] Read log line: 2026-01-16T11:31:47Z [net] pcp: Timeout
2026-01-16T11:31:49.507Z TRACE [shared::protobuf::event] creating new Event: LogExtractor(Log { log_timestamp: 1768563107000000, category: Net, threadname: "", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "pcp: Timeout" })) })
2026-01-16T11:31:49.507Z TRACE [log_extractor] published log into NATS: Event { timestamp: 1768563109507, peer_observer_event: Some(LogExtractor(Log { log_timestamp: 1768563107000000, category: Net, threadname: "", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "pcp: Timeout" })) })) }
2026-01-16T11:31:49.507Z TRACE [log_extractor] Read log line: 2026-01-16T11:31:47Z [net] pcp: Giving up after 3 tries
2026-01-16T11:31:49.507Z TRACE [shared::protobuf::event] creating new Event: LogExtractor(Log { log_timestamp: 1768563107000000, category: Net, threadname: "", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "pcp: Giving up after 3 tries" })) })
2026-01-16T11:31:49.507Z TRACE [log_extractor] published log into NATS: Event { timestamp: 1768563109507, peer_observer_event: Some(LogExtractor(Log { log_timestamp: 1768563107000000, category: Net, threadname: "", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "pcp: Giving up after 3 tries" })) })) }
2026-01-16T11:31:49.507Z TRACE [log_extractor] Read log line: 2026-01-16T11:31:47Z [net] portmap: Could not determine IPv6 default gateway
2026-01-16T11:31:49.507Z TRACE [shared::protobuf::event] creating new Event: LogExtractor(Log { log_timestamp: 1768563107000000, category: Net, threadname: "", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "portmap: Could not determine IPv6 default gateway" })) })
2026-01-16T11:31:49.507Z TRACE [log_extractor] published log into NATS: Event { timestamp: 1768563109507, peer_observer_event: Some(LogExtractor(Log { log_timestamp: 1768563107000000, category: Net, threadname: "", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "portmap: Could not determine IPv6 default gateway" })) })) }
2026-01-16T11:32:45.480Z TRACE [log_extractor] Read log line: 2026-01-16T11:32:45Z Adding fixed seeds as 60 seconds have passed and addrman is empty for at least one reachable network
2026-01-16T11:32:45.480Z TRACE [shared::protobuf::event] creating new Event: LogExtractor(Log { log_timestamp: 1768563165000000, category: Unknown, threadname: "", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "Adding fixed seeds as 60 seconds have passed and addrman is empty for at least one reachable network" })) })
2026-01-16T11:32:45.480Z TRACE [log_extractor] published log into NATS: Event { timestamp: 1768563165480, peer_observer_event: Some(LogExtractor(Log { log_timestamp: 1768563165000000, category: Unknown, threadname: "", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "Adding fixed seeds as 60 seconds have passed and addrman is empty for at least one reachable network" })) })) }
2026-01-16T11:32:45.480Z TRACE [log_extractor] Read log line: 2026-01-16T11:32:45Z Added 0 fixed seeds from reachable networks.
2026-01-16T11:32:45.481Z TRACE [shared::protobuf::event] creating new Event: LogExtractor(Log { log_timestamp: 1768563165000000, category: Unknown, threadname: "", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "Added 0 fixed seeds from reachable networks." })) })
2026-01-16T11:32:45.481Z TRACE [log_extractor] published log into NATS: Event { timestamp: 1768563165481, peer_observer_event: Some(LogExtractor(Log { log_timestamp: 1768563165000000, category: Unknown, threadname: "", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "Added 0 fixed seeds from reachable networks." })) })) }

thread 'test_integration_logextractor_unknown_with_category' (14727) panicked at extractors/log/tests/integration.rs:471:25:
assertion `left == right` failed
  left: 0
 right: 14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test_integration_logextractor_unknown_with_category
```

### PR DESCRIPTION
**Pull request by deadmanoz**
## Summary

- Move `LogDebugCategory::Net` assertions from inside `check_event` closures into `if let` guards so tests filter for the expected category rather than asserting on the first `UnknownLogMessage` received
- Document `setup_node`, `setup_two_connected_nodes`, and `check` test harness functions

Fixes https://github.com/peer-observer/peer-observer/issues/338

## Context

On slower CPUs (e.g. my trusty old Xeon E5-2630 v4 or even GitHub's own runners), bitcoind takes longer to initialise. This caused an event ordering race.

Three tests (`unknown_with_category`, `unknown_with_threadname_and_category`, `unknown_with_all_metadata`) matched the first `UnknownLogMessage` and asserted `category == Net`. On slower hardware, non-net messages (e.g. `dnsseed thread start` with category `Unknown`) arrive before any `[net]` line, causing assertion failures. Moving the category check into the `if let` guard lets the event loop skip non-matching messages and continue scanning until a `Net` category event arrives. If the log extractor breaks its category parsing, no event will ever match and the test will time out (preserves the original intent).

Here's a snippet from from logs identifying the failure of the reported issue (https://github.com/peer-observer/peer-observer/issues/338). Note that the test expects category `Net`, but the first `UnknownLogMessage` is from the `dnsseed` thread with category `Unknown`!

```
2026-02-11T02:04:28.780Z INFO  [log_extractor] Started reading lines from bitcoind log pipe at /tmp/nix-shell-319968-3831661800/.tmpocGJcs/bitcoind_pipe
2026-02-11T02:04:28.806Z TRACE [log_extractor] Read log line: 2026-02-11T02:04:27Z [dnsseed] dnsseed thread start
2026-02-11T02:04:28.806Z TRACE [shared::protobuf::event] creating new Event: LogExtractor(Log { log_timestamp: 1770775467000000, category: Unknown, threadname: "dnsseed", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "dnsseed thread start" })) })
2026-02-11T02:04:28.806Z TRACE [log_extractor] published log into NATS: Event { timestamp: 1770775468806, peer_observer_event: Some(LogExtractor(Log { log_timestamp: 1770775467000000, category: Unknown, threadname: "dnsseed", log_event: Some(UnknownLogMessage(UnknownLogMessage { raw_message: "dnsseed thread start" })) })) }
2026-02-11T02:04:28.806Z TRACE [log_extractor] Read log line: 2026-02-11T02:04:27Z [dnsseed] Loading addresses from DNS seed dummySeed.invalid.
```

## Testing
I have run these changes through CI on my fork, all green: https://github.com/deadmanoz/peer-observer/actions/runs/21893170475

### CODE REVIEW

File: extractors/log/tests/integration.rs [hunk 1]
```diff
@@ -82,6 +92,12 @@ fn setup_node(conf: corepc_node::Conf) -> corepc_node::Node {
     corepc_node::Node::from_downloaded_with_conf(&conf).unwrap()
 }
 
+/// Creates a two-node regtest topology:
+/// - node1 listens for inbound P2P connections
+/// - node2 connects to node1.
+///
+/// `node1_args` are appended as extra `bitcoind` CLI flags (e.g. `-debug=validation`) so tests
+/// can enable the specific logging needed to trigger the events they want to observe.
```
Comment (0xB10C) [inline extractors/log/tests/integration.rs]: mini nit: I think `///` are meant for documenting public (i.e. `pub`) functions that will end up in documentation. As these are private and only test specific, `//` should do the trick here too. But fine as is.
